# SPDX-FileCopyrightText: 2023 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Build with Alire

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: alire-project/setup-alire@v4
    - name: Build diana
      run: alr build
    - name: Build phases
      run: alr -C frontend build
    - name: Build RTL
      run: |
        ln -s -v bin exe
        cp -v share/diana/data/{PARSE,DIANA}.TBL .
        cp -v share/diana/data/ADA__LIB.CTL .
        mkdir ADA__LIB
        exe/loadgrmr
        rm -v {PARSE,DIANA}.TBL
        mv '$$$.TMP' PARSE.VM
        ln -s share/diana/rtl/_standrd.aa .
        share/diana/scripts/makepre